dist: xenial
language: python
jobs:
  include:
    - stage: test
      name: "Sanity"
      install: pip install -r requirements.txt
      # This is the ugliest form of testing but since this library doesn't have proper
      # tests yet, this is the best way to test that it works on a basic level.
      script: python -c "from steamapi import *"
      python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - stage: "Code Quality"
      install:
        - pip install -r requirements.txt
        - pip install pycodestyle
      name: "PEP-8"
      python: "3.7"
      script: python -m pycodestyle --ignore=E501,E741 .
